### PR TITLE
ci: Add eslint action

### LINKED ISSUE #201: Run linter during PR
We have ESLint rules to ensure a consistent code style, however nothing is checking this style during a PR. We should add https://github.com/marketplace/actions/eslint-action to ci.yml.

### PR DESCRIPTION
**Pull request by abmusse**
Resolves #201 

Workflow added from https://github.com/hallee/eslint-action#usage

### CODE REVIEW

**Comment by kadler** [comment]
It fails to install node-odbc due to
```
 gyp ERR! find Python 
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python 
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python 
gyp ERR! configure error 
```

It runs the action in the node10-slim docker container, so maybe it the container doesn't have the required dependencies to run node-gyp.

**Comment by abmusse** [comment]
> It runs the action in the node10-slim docker container, so maybe it the container doesn't have the required dependencies to run node-gyp.

Thats true but I don't think that causes the run to fail because odbc is an optional dep. Following the npm log there is the following:

```
added 445 packages from 1066 contributors and audited 1888 packages in 8.676s

25 packages are looking for funding
  run `npm fund` for details

found 6 low severity vulnerabilities
  run `npm audit fix` to fix them, or `npm audit` for details
Error Error: Received status code 401
    at IncomingMessage.res.on (/action/lib/request.js:13:25)
    at IncomingMessage.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)
{"message":"Bad credentials","documentation_url":"https://developer.github.com/v3"}
```

I'm thinking this error originates from a permissions issue from https://github.com/hallee/eslint-action/blob/master/lib/run.js#L103

**Comment by abmusse** [comment]
Alternatively we can use https://github.com/stefanoeb/eslint-action. This wont annotate the diffs of your pull requests with lint errors and warnings though. It uses the eslint cli interface.

**Comment by abmusse** [comment]
Using https://github.com/stefanoeb/eslint-action was successful although the [run](https://github.com/IBM/nodejs-itoolkit/pull/244/checks?check_run_id=675185548) logs a ton of `Warning: .then() only accepts functions but was passed: [object Object]`. Did some research and found this is caused by  https://npm.community/t/npm-ci-produces-a-tonn-of-excess-warnings-on-install/3261. Opened https://github.com/stefanoeb/eslint-action/pull/10 to resolve the problem.

**Comment by abmusse** [comment]
@kadler how about we simply run eslint during our CI action. Something similar to the suggestion here: https://github.com/stefanoeb/eslint-action/issues/8#issuecomment-640190126

**Comment by kadler** [comment]
Yeah, I think it would be better to call out to `npm run lint` (which as an aside sounds like it would be better as `npm run linter` instead, but our test and test-integration scripts follow the same style so :shrug:)

**Pull request merged**
