### PR TITLE
chore: Remove All Rights Reserved from License text

### PR DESCRIPTION
**Pull request by dmabupt**

### CODE REVIEW

**Comment by kadler** [comment]
Looks like the linter is complaining that the commits are not following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/). I would recommend reading through that. I think the chore prefix fits here. Also, maybe something more descriptive like "chore: Remove All Rights Reserved from License text"

**Comment by abmusse** [comment]
> Looks like the linter is complaining that the commits are not following [conventional commits](https://www.conventionalcommits.org/en/v1.0.0/). I would recommend reading through that. I think the chore prefix fits here. Also, maybe something more descriptive like "chore: Remove All Rights Reserved from License text"

Yes I agree chore fits this well.

**Comment by abmusse** [comment]
@dmabupt  You should join the IBM org on github that way the DCO bot will stop flagging your commits.

**Comment by dmabupt** [comment]
> @dmabupt
> You should join the IBM org on github.
> 
> Then the DCO bot will stop flagging your commits to be signed off.

Yes, I just do not know how to join the org :-)

**Comment by kadler** [comment]
@dmabupt I've sent a message how to link your id in Slack. Also, for DCO bot to know you're a member of the org you also have to sign your commits. Without signing, anyone could configure their git client to use your id and claim to be you and DCO bot would have no way to verify.

https://github.com/probot/dco#skipping-sign-off-for-organization-members
https://help.github.com/en/github/authenticating-to-github/signing-commits
https://stackoverflow.com/a/30467819

**Comment by dmabupt** [comment]
> @dmabupt I've sent a message how to link your id in Slack. Also, for DCO bot to know you're a member of the org you also have to sign your commits. Without signing, anyone could configure their git client to use your id and claim to be you and DCO bot would have no way to verify.
> 
> https://github.com/probot/dco#skipping-sign-off-for-organization-members
> https://help.github.com/en/github/authenticating-to-github/signing-commits
> https://stackoverflow.com/a/30467819

Thanks, Seems now I am the member of the org.

**Pull request merged**
