### PR TITLE
docs: Simplify main README to contain basic info

### LINKED ISSUE #257: Simplify readme
The readme has a lot of info on it that is better suited to be read from the docs. We should simplify the readme to contain some basic info about the package and maybe show a simple example and then refer people to the docs for more detailed info.

### PR DESCRIPTION
**Pull request by abmusse**
Resolves #257

### CODE REVIEW

**Comment by abmusse** [comment]
FYI Moved  the transport information to https://nodejs-itoolkit.readthedocs.io/en/latest/Connection.html#transports

**Comment by kadler** [comment]
Definitely good removals, but now it seems very barren. I'd like to see some basic intro info, like what we have on the docs intro page. eg. more info on what it does, why it's useful, etc.

https://medium.com/@meakaakka/a-beginners-guide-to-writing-a-kickass-readme-7ac01da88ab3

**Comment by abmusse** [comment]
Need to resolve a simple conflict:

image

**Comment by abmusse** [comment]
@kadler This is ready for re-review

**Pull request merged**
