### PR TITLE
docs: Use sphinx-js

### PR DESCRIPTION
**Pull request by abmusse**
Resolves https://github.com/IBM/nodejs-itoolkit/issues/95

We now use [sphinx-js](https://github.com/mozilla/sphinx-js) for documentation.

### CODE REVIEW

**Comment by abmusse** [comment]
@kadler 

I created an initial draft of docs using `sphnix-js`. Would it be better to split this into multiple PRs?

**Comment by kadler** [comment]
I think it's fine as-is. I set up a readthedocs project, but it's failing to build because sphinx-js is not installed by default. Can you add a [docs/requirements.txt](https://pip.pypa.io/en/stable/user_guide/#requirements-files) and add it to a (new) readthedocs [config file](https://docs.readthedocs.io/en/stable/config-file/v2.html#supported-settings).

Then, the [build](https://readthedocs.org/projects/nodejs-itoolkit/builds/10877621/) should work and we can preview/review the docs at https://nodejs-itoolkit.readthedocs.io/en/use-sphinx-js/

**Comment by abmusse** [comment]
@kadler I've added the requested files. Can you run another build?

**Comment by kadler** [comment]
```
Deprecated.js:iPgm(70):65: (WARNING/2) Explicit markup ends without a blank line; unexpected unindent.
Deprecated.js:iConn(549):93: (WARNING/2) Explicit markup ends without a blank line; unexpected unindent.
Deprecated.js:restConfig(529):12: (WARNING/2) Inline emphasis start-string without end-string.
Deprecated.js:restConfig(529):13: (WARNING/2) Inline emphasis start-string without end-string.

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/nodejs-itoolkit/envs/use-sphinx-js/lib/python3.7/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/nodejs-itoolkit/envs/use-sphinx-js/lib/python3.7/site-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/nodejs-itoolkit/envs/use-sphinx-js/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 347, in build_update
    len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/nodejs-itoolkit/envs/use-sphinx-js/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 360, in build
    updated_docnames = set(self.read())
  File "/home/docs/checkouts/readthedocs.org/user_builds/nodejs-itoolkit/envs/use-sphinx-js/lib/python3.7/site-packages/sphinx/builders/__init__.py", line 472, in read
    self.env.doc2path(self.config.master_doc))
sphinx.errors.SphinxError: master file /home/docs/checkouts/readthedocs.org/user_builds/nodejs-itoolkit/checkouts/use-sphinx-js/docs/contents.rst not found

Sphinx error:
master file /home/docs/checkouts/readthedocs.org/user_builds/nodejs-itoolkit/checkouts/use-sphinx-js/docs/contents.rst not found
```

**Comment by abmusse** [comment]
Looks like we need to `master_doc = 'index'` to `conf.py` https://github.com/readthedocs/readthedocs.org/issues/2569#issuecomment-485117471

**Comment by kadler** [comment]
The build has passed: https://nodejs-itoolkit.readthedocs.io/en/use-sphinx-js

**Comment by kadler** [comment]
I'd like to see the intro page be the pain page. Right now when you go to the docs you just get an index, which is not the best user experience / first impression.

**Comment by abmusse** [comment]
> I'd like to see the intro page be the pain page. Right now when you go to the docs you just get an index, which is not the best user experience / first impression.

So I moved the contents of `intro.rst` into `index.rst` then ran a new build.

https://nodejs-itoolkit.readthedocs.io/en/use-sphinx-js/

**Comment by kadler** [comment]
FYI @abmusse there is a webhook setup already so any pushes automatically trigger a build.

**Pull request merged**
