### PR TITLE
refactor: Remove Toolkit.js

### LINKED ISSUE #161: Remove Toolkit.js
For v1.0.0-alpha  #33 [Toolkit.js](https://github.com/IBM/nodejs-itoolkit/blob/master/lib/Toolkit.js) was added.
 
This consolidated the following classes into one Toolkit Class:

- [x] iDataQueue
- [x] iNetwork
- [x] iObj
- [x] iProd
- [x] iUserSpace
- [x] iWork

For v1.0.0 we would like to deprecate these classes. 

Similar to SqlCall https://github.com/IBM/nodejs-itoolkit/pull/117#pullrequestreview-362953801, Toolkit.js was added in 1.0 development, but we haven't shipped 1.0 yet, so it doesn't make much sense to deprecate it. Instead we should just remove it and move the code back in to each respective class.

Need to remove each class from Toolkit
-  code
-  docs
-  tests

### PR DESCRIPTION
**Pull request by abmusse**
Resolves #161

### CODE REVIEW

**Comment by abmusse** [comment]
The above was copied into the methods that use it

https://github.com/IBM/nodejs-itoolkit/blob/master/lib/Deprecated.js#L821

https://github.com/IBM/nodejs-itoolkit/blob/master/lib/Deprecated.js#L2730

Probably should have been removed it after copying it over.

**Comment by kadler** [comment]
Ah, it was used in multiple places then (like errno)?

**Comment by abmusse** [comment]
No each was only used in one spot.

IpToNum was only used in [getNetInterfaceData](https://github.com/IBM/nodejs-itoolkit/blob/376cc5a3cc61c7867686205c537ffcd67e34c8eb/lib/Toolkit.js#L338) and sysvalArray was only used in [getSysValue](https://github.com/IBM/nodejs-itoolkit/blob/376cc5a3cc61c7867686205c537ffcd67e34c8eb/lib/Toolkit.js#L1819)

**Comment by kadler** [comment]
Oh, then yeah they should have been removed when they were moved to the other file. Oh well.

**Pull request merged**
