### PR TITLE
Refactoring and Renaming

### LINKED ISSUE #23: Refactor Code for 1.0
This entire repository needs a ~little~ lot of TLC. For instance, it seems to have been written with no deference to DRY principles. For example, `lib/idataq.js` has a class with 3 functions, `sendToDataQueue`, `receiveFromDataQueue`, and `clearDataQueue`. 90% of the code in these functions is the same, the only difference is the iPgm parameters that are added at the beginning of functions. The rest of the code is more like... looping and waiting for the results to come back, and I'm not even sure that code is written all that great.

While I'm linting (#21), I'm going to get familiar with the program and then I'll propose what we should do to abstract a lot of this out into a single function, then pass the parameters that need to be sent to the pgm.

### PR DESCRIPTION
**Pull request by markdirish**
V1.0 devThis is the same PR as #31, but since I hard reset the branch to remove my accidental push (in the future I don't think we should do this, since hard resetting is sort of antithetical to git), I had to remove the commits from my fork as well.

This fixes #23 (partially) and #24 

Note: Throughout this merge, have named class files the same as the class name, with a capital letter. It seems that people online are split about whether class files should be capital (like Java and TypeScript), or lowercase (like simple script files).

Big changes in this merge:

- Combined iDataQueue, iNetwork, iObj, iProd, iUserSpace, and iWork into a Toolkit class. Old classes still can be called in the API, but are deprecated. They are all subbed in the bottom of Toolkit.js
- Combined all of the functions that generate commands (iCmd, iQsh, iSh) into a CommandGenerator class and created static classes. Again, old calls still work but are deprecated, and live in CommandGenerator.js for now.
- iConn renamed to Connection.js
- iSql renamed to SqlGenerator.js (since the class really just generates some SQL then returns xml when xml() is called).

Before this is merged in, I will try to add jsDocs, but its some big changes here so I'd rather get this out before mucking with that. I will also check that deprecation warnings are standardized. I couldnt get the util.deprecated() Node.js to work with eslint, not sure if theres just a coding pattern in javascript I'm not familiar with.

A few MINOR logic changes to use things like ternary operator.

### CODE REVIEW

**Comment by kadler** [comment]
It seems there's increasingly more and more that should be rethough and redesigned, so I'd almost prefer we just broke compatibility and made something usable.

@ThePrez What do you think? Is it worth keeping around compatibility? We never did declare it "1.0", but I suspect there's quite a few people using it already. We could always keep the old "0.x" code around in a separate branch for a while if people need fixes.

**Comment by ThePrez** [comment]
There are a lot of people using the current (now deprecated) stuff.

I declare that we continue to ship it in v1.0 with clear and strong wording about the massive deprecation. 

In v2.x, remove the functions completely.

When is v2.x? That will become more clear when our LTS strategy is finalized.

**Comment by ThePrez** [comment]
We should keep 0.x around in its own branch regardless, of course

**Comment by abmusse** [comment]
LGTM

**Comment by markdirish** [comment]
@kadler I moved all of the deprecated functions in Toolkit.js to Deprecated.js, and for good measure all other deprecated code too (iPgm, iSql). When/If we decide to eliminate this code, we should just be able to delete Deprecate.js and fix the imports in itoolkit.js.

I also removed the CommandGenerator.js class and the 3 functions contained in it are now just const functions with names generateCmdXml, generateQshXml, and generateShXml, kept in the commands.js file.

**Pull request merged**
